services:
  mysql:
    image: mysql:5.7
    container_name: db_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Catolica@SC'
      MYSQL_DATABASE: 'BaseN3'
      MYSQL_USER: 'wpadmin'
      MYSQL_PASSWORD: 'admin@pass'
    networks:
      - app_net

  wordpress:
    image: wordpress:latest
    container_name: app_wordpress
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: 'wpadmin'
      WORDPRESS_DB_PASSWORD: 'admin@pass'
      WORDPRESS_DB_NAME: 'BaseN3'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost/prova');
        define('WP_SITEURL', 'http://localhost/prova');
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_admin_gui
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'Catolica@SC'
    networks:
      - app_net

  nginx:
    image: nginx:stable-alpine
    container_name: web_proxy
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./nginx_config/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge